### ISSUE TITLE
WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!

### ISSUE THREAD

**Issue by sa-etc** [filemage/google-cloud-terraform-quickstart#1]
Is there any way to utilize the same host key for each server on the backend? With the managed instance group the nodes will be scaling periodically and some nodes may be deleted due to errors. I don't want to manually have to change the keys for each host.

**Comment by filemage2** [comment]
Please contact support@filemage.io for question about how to deploy and configure the product.
